---
- hosts: all
  connection: "{{connection or 'paramiko'}}"
  become: yes
  become_method: sudo
  vars_files:
    - vars/server.yml
  pre_tasks:
    - name: Upgrade all packages
      yum:
        name=*
        state=latest

    - stat: path=/selinux/enforce
      register: selinux

  roles:
    - {role: 'kernel'}
    - {role: 'resmo.ntp'}
    - {role: 'mrlesmithjr.timezone'}
    - {role: 'geerlingguy.repo-epel'}
    - {role: 'geerlingguy.repo-remi'}
    - {role: 'mikegleasonjr.swap', tags: 'swap', when: "ansible_memtotal_mb < 1000"}
    - {role: 'tools'}
    - {role: 'memcached', when: "ansible_memtotal_mb > 2000"}
    - {role: 'redis'}
    - {role: 'bertvv.mariadb'}
    - {role: 'geerlingguy.nginx'}
    - {role: 'php', tags: 'php'}
    - {role: 'ioncube', tags: 'ioncube', when: php_version >= 'php70'}
    - {role: 'selinux',  when: selinux.stat.exists == True}
    - {role: 'monit'}
    - {role: 'geerlingguy.firewall', tags: 'firewall'}
    - {role: 'keitaro'}
