---
php_version: 'php56'
timezone: Europe/Moscow
swap_size: "2048M"
os_user: nginx

keitaro:
  path: /var/www/keitaro

# MariaDB
mariadb_version: 10.1
mariadb_databases:
  - "{{ db_name }}"
mariadb_users:
  - name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL,GRANT"

# NGinx
nginx_worker_processes: auto
nginx_remove_default_vhost: true
nginx_extra_http_options: |
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;
nginx_vhosts:
  - listen: 80 default_server
    server_name: _
    root: "{{ keitaro.path }}"
    index: index.php
    charset: utf-8
    error_log: /var/log/nginx/error.log
    extra_parameters: |
      location ~* \.(jpg|jpeg|gif|png|js|css|txt|zip|ico|gz|csv)$ {
        expires 10d;
      }

      location ~* /(var|lib|application)/.*$ {
        return 403;
      }

      location ~* \.(htaccess|ini|dat)$ {
        return 403;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }

      location / {
        access_log off;
        try_files $uri $uri/ /index.php?$args;
      }

      location /admin {
        access_log /var/log/nginx/admin.access.log combined buffer=16k;
      }


# Firewall
firewall_allowed_tcp_ports:
  - "22"
  - "443"
  - "80"
