---
- name: install tools
  yum:
    name={{item}}
    state=present

  with_items:
    - nano
    - htop
    - httpd-tools

- name: Remove require tty
  tags: tty
  lineinfile: regexp="requiretty" dest=/etc/sudoers state=absent

- name: Remove require tty - alt
  lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent