---
- name: prepare keitaro dir
  file:
    path={{ keitaro.path }}
    state=directory
    owner={{ os_user }}
    group={{ os_user }}
    mode=0777

- name: download installer
  tags: keitaro
  get_url:
    url=http://keitarotds.com/getfile/install
    dest={{ keitaro.path }}/install.php

- name: install Keitaro TDS
  tags: keitaro
  shell: |
    cd {{ keitaro.path }} && \
    sudo -u {{os_user}} php install.php install \
        --ip={{ license_ip }}  \
        --key={{ license_key }} \
        --db-user={{ db_user }} \
        --db-name={{ db_name }} \
        --db-password='{{ db_password }}' \
        --admin-login={{ admin_login }} \
        --admin-password='{{ admin_password }}' \
        --draft-storage=redis

- name: Add cron task
  tags: keitaro
  cron:
    user="{{os_user}}"
    name="keitaro"
    job="php {{ keitaro.path }}/cron.php"
